<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Ivan Kurniawan Prasetyo',
                'phone' => '08985005660',
                'id_membership' => NULL,
                'email' => 'ivankp@technopartner.id',
                'password' => '$2y$10$JgoY2K77XGHLyvuKjQZHKei5.loCHfzCR573c5n4Iy5OlcvxEAmj.',
                'id_city' => 501,
                'gender' => 'Male',
                'provider' => 'Tri',
                'birthday' => '1988-01-10',
                'phone_verified' => '1',
                'email_verified' => '1',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:18:32',
                'updated_at' => '2018-05-09 16:18:32',
            ),
            1 => 
            array (
                'id' => 3,
                'name' => 'Haniyah Imtiyaz',
                'phone' => '085866937804',
                'id_membership' => NULL,
                'email' => 'haniyah.imtiyaz@technopartner.id',
                'password' => '$2y$10$gNOiaK3g13K5Ul6fNobv4.ERbd7QX7UGRiOHneiD1Lk9Xp2IuTFn.',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Indosat',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:21:57',
                'updated_at' => '2018-05-09 16:21:57',
            ),
            2 => 
            array (
                'id' => 4,
                'name' => 'Guntur Satrya Saputro',
                'phone' => '0811255501',
                'id_membership' => NULL,
                'email' => 'guntur@technopartner.id',
                'password' => '$2y$10$1HbQbgWsNgWMnHtViot08.j6Vrl4xuSut6QpL7nUH5bfCfdXnvXlm',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Telkomsel',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '1',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:22:09',
                'updated_at' => '2018-05-09 16:22:09',
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Dwi Heru Budi Waspodo',
                'phone' => '083847090002',
                'id_membership' => NULL,
                'email' => 'dwiheru@technopartner.id',
                'password' => '$2y$10$vdo59DrFthn04wBY78pfQejWaWhqQ.uawd9XbbIpfCmaXj/tyJavy',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Axis',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:22:34',
                'updated_at' => '2018-05-09 16:22:34',
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Tri Wardana',
                'phone' => '089674657270',
                'id_membership' => NULL,
                'email' => 'tri.wardana@technopartner.id',
                'password' => '$2y$10$IUh6HcjPoDJs1lAZbAOGUej5GC6FipB/Vg4V4i0pINhTQcGxXx9oS',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Tri',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:22:58',
                'updated_at' => '2018-05-09 16:22:58',
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Adi Baswendra',
                'phone' => '082251401717',
                'id_membership' => NULL,
                'email' => 'adibaswendra@technopartner.id',
                'password' => '$2y$10$Cr99veqlMeixF46GV3T5VeV8WNqw3FIPlK.ao094jE/uAghq7PB.C',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Telkomsel',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:23:23',
                'updated_at' => '2018-05-09 16:23:23',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Niki Hidayati',
                'phone' => '081329649882',
                'id_membership' => NULL,
                'email' => 'nikihidayati@technopartner.id',
                'password' => '$2y$10$Pu2p0ZWdjDt2ob.kF5YJ8.l5uDq9ZoNRaiL8SeuFmKdJFZ77uCZHm',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Telkomsel',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:23:44',
                'updated_at' => '2018-05-09 16:23:44',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Wahyu Hadi',
                'phone' => '082225501351',
                'id_membership' => NULL,
                'email' => 'wahyuhadi@technopartner.id',
                'password' => '$2y$10$0WDJh.yLM2q0OXcKq/2CqOxNfuH6UYq8rXnMyxiSJzavGmUJbLc3e',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Telkomsel',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:25:44',
                'updated_at' => '2018-05-09 16:25:44',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Denis Tirta',
                'phone' => '081379100375',
                'id_membership' => NULL,
                'email' => 'denistirta@technopartner.id',
                'password' => '$2y$10$8FO7/C7b/NgpV8OyhuVb2edwmfj24zMjsl.2vpGxGDKRqrRwL7gzC',
                'id_city' => 501,
                'gender' => NULL,
                'provider' => 'Telkomsel',
                'birthday' => NULL,
                'phone_verified' => '1',
                'email_verified' => '0',
                'level' => 'Super Admin',
                'points' => 0,
                'android_device' => NULL,
                'ios_device' => NULL,
                'is_suspended' => '0',
                'remember_token' => NULL,
                'created_at' => '2018-05-09 16:26:37',
                'updated_at' => '2018-05-09 16:26:37',
            ),
        ));
        
        
    }
}